remove support for CentOS/8 since it is EOL
CentOS/8 has reached End-Of-Life:
    https://www.centos.org/centos-linux-eol/

We're doing this now rather than later because CentOS can not be
upgraded with 'dnf update' or 'yum update' which obviously breaks our
build.

Here is a link to a centos forum post discussing this error and noting that
it WILL NOT be fixed by Redhat and users must instead migrate to a different
distribution:

    https://forums.centos.org/viewtopic.php?f=54&t=78708

Here is the error:
-----------------------------------------------------------------------
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
The command '/bin/sh -c yum update -y &&        yum install -y createrepo_c yum-utils sudo dnf-plugins-core epel-release &&     yum groupinstall -y 'Development Tools' &&     yum config-manager --set-enabled powertools &&     yum makecache' returned a non-zero code: 1

Error: Process completed with exit code 1.
-----------------------------------------------------------------------